#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------

- name: Create docker-registry service
  stat: path=/etc/init.d/docker-registry
  register: st0

- template:
    src: etc/init.d/docker-registry
    dest: /etc/init.d/docker-registry
    owner: root
    mode: 0755
  when: not st0.stat.exists

- name: Start Docker repository service
  shell: bash -c "/usr/sbin/service docker-registry start"

- name: Test repository
  shell: docker images | grep my_busybox | wc -l
  register: busy_box

- command: docker pull busybox
  when: "'0' in busy_box.stdout_lines[0]"

- command: docker tag busybox "{{ inventory_hostname }}:{{ docker_registry_port }}/my_busybox"
  when: "'0' in busy_box.stdout_lines[0]"

- command: docker push "{{ inventory_hostname }}:{{ docker_registry_port }}/my_busybox"
  when: "'0' in busy_box.stdout_lines[0]"
