- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - storlets-functional
    gate:
      jobs:
        - storlets-functional

- job:
    name: storlets-functional
    pre-run: playbooks/storlets-functional/pre.yaml
    run: playbooks/storlets-functional/run.yaml
    timeout: 2400
