- project:
    templates:
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - storlets-functional:
            irrelevant-files:
              - ^(api-ref|doc|releasenotes)/.*$
              - ^(.gitreview|.mailmap|AUTHORS|CHANGELOG)$
    gate:
      jobs:
        - storlets-functional

- job:
    name: storlets-functional
    pre-run: playbooks/storlets-functional/pre.yaml
    run: playbooks/storlets-functional/run.yaml
    post-run: playbooks/storlets-functional/post.yaml
    timeout: 2400
